user-tenant-service-tests initial commit
sourcefuse/j-arc pull request #36
Opened 2023-06-26 12:21 UTC by AdilSDE

## Description

1. Added Integration and Unit test cases  for User Tenant Service.
2.Have use Junit 5  and Mockito(Mockito is a java based mocking framework, used in conjunction with other testing frameworks such as JUnit and TestNG.)
3.Have used MockMvc for  writing integration test cases.
(The Spring MVC Test framework, also known as MockMvc, provides support for testing Spring MVC applications. It performs full Spring MVC request handling but via mock request and response objects instead of a running server)

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-27 05:42 UTC, harshadk-sourcefuse requested changes
not have added similar comments check the code and update the similar code accordingly.

2023-06-27 05:42 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/integration/GroupControllerTests.java
> +      );
Not Needed as `      .andExpect(MockMvcResultMatchers.status().isInternalServerError())`
is doing the same thing

2023-06-27 05:42 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/integration/GroupControllerTests.java
> +      .thenThrow(new ResponseStatusException(HttpStatus.INTERNAL_SERVER_ERROR));
count method will throw Exception related to postgres will not throw ResponseStatusException on its own

2023-06-27 05:42 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/integration/GroupControllerTests.java
> +    MockCurrentUserSession.setCurrentLoggedInUser(null, null, null);
Move this code in beforeEach don't need to repeat this as all API's should be authenticated

2023-06-27 05:42 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/integration/GroupControllerTests.java
> +  }
repeated method create move this method to some static class

2023-06-27 05:42 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/integration/UserGroupsControllerTests.java
> +    mockMvc = MockMvcBuilders.standaloneSetup(userGroupsController).build();
remove this line since its already in beforeEach

2023-06-27 05:42 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/unit/TenantUserControllerUnitTests.java
> +      .save(ArgumentMatchers.any(User.class));
does not match the description of test case

2023-06-28 07:42 UTC, harshadk-sourcefuse approved these changes

2023-06-30 09:10 UTC, mlakdawala-sf reviewed
Can you attach the code coverage with this please

2023-07-04 09:54 UTC, merged