Sandbox example of audit and notification service
sourcefuse/j-arc pull request #37
Opened 2023-06-30 11:14 UTC by harshadk-sourcefuse

## Description
Sandbox examples of 
- audit service 
- notification-service
  - PubNub
  - Java Mailer
  - Twilio
 Also Integrated Authorization on notification-service and audit-service API's

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [X] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-14 10:00 UTC, mlakdawala-sf requested changes
Apart from the comments, rest looks fine to me

2023-07-14 10:00 UTC, mlakdawala-sf commented on sandbox/notification-javamailer-example/src/main/java/com/notification/example/javamailer/controllers/PingController.java
> +  public ResponseEntity<String> ping() {
instead of this there is a health check package u can get it from auth service

2023-07-14 10:00 UTC, mlakdawala-sf commented on sandbox/notification-pubnub-example/src/main/java/com/notification/example/pubnub/controllers/PingController.java
> +    return new ResponseEntity<>("ping success", HttpStatus.OK);
Same here

2023-07-14 10:00 UTC, mlakdawala-sf commented on sandbox/notification-twilio-example/src/main/java/com/notification/example/twilio/controllers/PingController.java
> +    return new ResponseEntity<>("ping success", HttpStatus.OK);
Same here

2023-07-14 11:00 UTC, harshadk-sourcefuse commented on sandbox/notification-javamailer-example/src/main/java/com/notification/example/javamailer/controllers/PingController.java
> +  public ResponseEntity<String> ping() {
Done, Deleted this file

2023-07-14 11:00 UTC, harshadk-sourcefuse commented on sandbox/notification-pubnub-example/src/main/java/com/notification/example/pubnub/controllers/PingController.java
> +    return new ResponseEntity<>("ping success", HttpStatus.OK);
Done, Deleted this file

2023-07-14 11:00 UTC, harshadk-sourcefuse commented on sandbox/notification-twilio-example/src/main/java/com/notification/example/twilio/controllers/PingController.java
> +    return new ResponseEntity<>("ping success", HttpStatus.OK);
Done, Deleted this file

2023-07-17 11:54 UTC, mlakdawala-sf approved these changes

2023-07-21 10:43 UTC, yeshamavani reviewed
Can we keep the core and auth-lib changes as a separate PR

2023-07-21 11:55 UTC, harshadk-sourcefuse commented
> Can we keep the core and auth-lib changes as a separate PR

changes are interdependent

2023-07-24 09:41 UTC, merged