initial commit for user-tenant-sandbox-example
sourcefuse/j-arc pull request #41
Opened 2023-07-10 11:19 UTC by AdilSDE

## Description
User-Tenant-Services sandbox example created ,so that A consumer/user can easily access the Api's through swagger Open API.

“The OpenAPI Specification (OAS) defines a standard, language-agnostic interface to RESTful APIs which allows both humans and computers to discover and understand the capabilities of the service without access to source code, documentation, or through network traffic inspection.”

Fixes #40

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-14 06:31 UTC, harshadk-sourcefuse requested changes
check for similar changes as well in another files

2023-07-14 06:31 UTC, harshadk-sourcefuse commented on services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/TenantController.java
> +    "'" +
```suggestion
"','" +
```

2023-07-14 10:34 UTC, mlakdawala-sf requested changes

2023-07-14 10:34 UTC, mlakdawala-sf commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/unit/TenantUserControllerUnitTests.java
> +                currentUser
formatting issue

2023-07-14 10:34 UTC, mlakdawala-sf commented on services/user-tenant-service/src/test/java/com/sourcefuse/jarc/services/usertenantservice/unit/TenantUserControllerUnitTests.java
> +                currentUser
formatting issue

2023-07-14 10:34 UTC, mlakdawala-sf commented on services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserTenantController.java
> +    "'" +
can we make this in a single quote statement, and fix this in other places

2023-07-14 10:34 UTC, mlakdawala-sf commented on services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserGroupController.java
> +    "isAuthenticated() && hasAnyAuthority('" +
```suggestion
    "isAuthenticated() && hasAuthority('" +
```

2023-07-14 10:34 UTC, mlakdawala-sf commented on services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/UserGroupController.java
> +    "isAuthenticated() && hasAnyAuthority('" +
Has any authority for multiple permission case, where the api can run through either of the permissions provided

2023-07-14 10:34 UTC, mlakdawala-sf commented on services/user-tenant-service/src/main/java/com/sourcefuse/jarc/services/usertenantservice/controller/TenantUserController.java
> +    "'," +
please fix it across the app

2023-07-17 12:00 UTC, mlakdawala-sf requested changes

2023-07-17 12:00 UTC, mlakdawala-sf commented on sandbox/user-tenant-service-example/src/main/java/com/example/usertenantserviceexample/controller/PingController.java
> +  public ResponseEntity<String> ping() {
use health check package, check pom file of auth service

2023-07-21 09:36 UTC, mlakdawala-sf approved these changes

2023-07-24 05:18 UTC, harshadk-sourcefuse approved these changes

2023-07-24 10:41 UTC, merged